name: chromatic

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: Preview
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Package dependencies
      run: yarn install

    - name: Build and Deploy
      run: yarn chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} -b build-sb --exit-zero-on-changes
