name: chromatic

on: [push]

jobs:
  deploy:
    name: Preview
    runs-on: ubuntu-latest
    if: github.base_ref == 'master'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: yarn install

    - name: Chromatic
      run: yarn chromatic --project-token ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
